Microsoft Windows [Version 10.0.19045.4651]
(c) Microsoft Corporation. All rights reserved.

C:\WINDOWS\system32>python --version
Python 3.12.4

C:\WINDOWS\system32>python -m pip install --upgrade pip
Requirement already satisfied: pip in c:\users\hp\appdata\local\programs\python\python312\lib\site-packages (24.2)

C:\WINDOWS\system32>pip install django
Collecting django
  Downloading Django-5.1-py3-none-any.whl.metadata (4.2 kB)
Collecting asgiref<4,>=3.8.1 (from django)
  Downloading asgiref-3.8.1-py3-none-any.whl.metadata (9.3 kB)
Collecting sqlparse>=0.3.1 (from django)
  Downloading sqlparse-0.5.1-py3-none-any.whl.metadata (3.9 kB)
Collecting tzdata (from django)
  Downloading tzdata-2024.1-py2.py3-none-any.whl.metadata (1.4 kB)
Downloading Django-5.1-py3-none-any.whl (8.2 MB)
   ---------------------------------------- 8.2/8.2 MB 3.7 MB/s eta 0:00:00
Downloading asgiref-3.8.1-py3-none-any.whl (23 kB)
Downloading sqlparse-0.5.1-py3-none-any.whl (44 kB)
Downloading tzdata-2024.1-py2.py3-none-any.whl (345 kB)
Installing collected packages: tzdata, sqlparse, asgiref, django
Successfully installed asgiref-3.8.1 django-5.1 sqlparse-0.5.1 tzdata-2024.1

C:\WINDOWS\system32>pip install django==3
Collecting django==3
  Downloading Django-3.0-py3-none-any.whl.metadata (3.6 kB)
Collecting pytz (from django==3)
  Downloading pytz-2024.1-py2.py3-none-any.whl.metadata (22 kB)
Requirement already satisfied: sqlparse>=0.2.2 in c:\users\hp\appdata\local\programs\python\python312\lib\site-packages (from django==3) (0.5.1)
Requirement already satisfied: asgiref~=3.2 in c:\users\hp\appdata\local\programs\python\python312\lib\site-packages (from django==3) (3.8.1)
Downloading Django-3.0-py3-none-any.whl (7.4 MB)
   ---------------------------------------- 7.4/7.4 MB 3.7 MB/s eta 0:00:00
Downloading pytz-2024.1-py2.py3-none-any.whl (505 kB)
Installing collected packages: pytz, django
  Attempting uninstall: django
    Found existing installation: Django 5.1
    Uninstalling Django-5.1:
      Successfully uninstalled Django-5.1
Successfully installed django-3.0 pytz-2024.1

C:\WINDOWS\system32>cd C:\Users\All Users

C:\Users\All Users>cd Desktop

C:\Users\All Users\Desktop>cd demo
The system cannot find the path specified.

C:\Users\All Users\Desktop>cd \Users\HP\Desktop

C:\Users\HP\Desktop>cd demo

C:\Users\HP\Desktop\demo>django -admin startproject mysite
'django' is not recognized as an internal or external command,
operable program or batch file.

C:\Users\HP\Desktop\demo>django-admin startproject mysite

C:\Users\HP\Desktop\demo>cd mysite

C:\Users\HP\Desktop\demo\mysite>django-admin startapp djangoapp

C:\Users\HP\Desktop\demo\mysite>python manage.py runserver
Watching for file changes with StatReloader
Performing system checks...

System check identified no issues (0 silenced).

You have 17 unapplied migration(s). Your project may not work properly until you apply the migrations for app(s): admin, auth, contenttypes, sessions.
Run 'python manage.py migrate' to apply them.
August 12, 2024 - 19:42:39
Django version 3.0, using settings 'mysite.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CTRL-BREAK.
[12/Aug/2024 19:43:25] "GET / HTTP/1.1" 200 16351
[12/Aug/2024 19:43:25] "GET /static/admin/css/fonts.css HTTP/1.1" 200 423
[12/Aug/2024 19:43:25] "GET /static/admin/fonts/Roboto-Regular-webfont.woff HTTP/1.1" 200 85876
[12/Aug/2024 19:43:25] "GET /static/admin/fonts/Roboto-Bold-webfont.woff HTTP/1.1" 200 86184
[12/Aug/2024 19:43:25] "GET /static/admin/fonts/Roboto-Light-webfont.woff HTTP/1.1" 200 85692
Not Found: /favicon.ico
[12/Aug/2024 19:43:25] "GET /favicon.ico HTTP/1.1" 404 1972

C:\Users\HP\Desktop\demo\mysite>
C:\Users\HP\Desktop\demo\mysite>
C:\Users\HP\Desktop\demo\mysite>
C:\Users\HP\Desktop\demo\mysite>python manage.py runserver
Watching for file changes with StatReloader
Performing system checks...

System check identified no issues (0 silenced).

You have 17 unapplied migration(s). Your project may not work properly until you apply the migrations for app(s): admin, auth, contenttypes, sessions.
Run 'python manage.py migrate' to apply them.
August 12, 2024 - 19:45:00
Django version 3.0, using settings 'mysite.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CTRL-BREAK.
[12/Aug/2024 19:45:05] "GET / HTTP/1.1" 200 16351
[12/Aug/2024 19:45:05] "GET /static/admin/css/fonts.css HTTP/1.1" 304 0
[12/Aug/2024 19:45:05] "GET /static/admin/fonts/Roboto-Bold-webfont.woff HTTP/1.1" 304 0
[12/Aug/2024 19:45:05] "GET /static/admin/fonts/Roboto-Regular-webfont.woff HTTP/1.1" 304 0
[12/Aug/2024 19:45:05] "GET /static/admin/fonts/Roboto-Light-webfont.woff HTTP/1.1" 304 0
[12/Aug/2024 19:46:16] "GET / HTTP/1.1" 200 16351
[12/Aug/2024 19:46:16] "GET /static/admin/css/fonts.css HTTP/1.1" 200 423
[12/Aug/2024 19:46:16] "GET /static/admin/fonts/Roboto-Bold-webfont.woff HTTP/1.1" 200 86184
[12/Aug/2024 19:46:16] "GET /static/admin/fonts/Roboto-Regular-webfont.woff HTTP/1.1" 200 85876
[12/Aug/2024 19:46:16] "GET /static/admin/fonts/Roboto-Light-webfont.woff HTTP/1.1" 200 85692
Not Found: /favicon.ico
[12/Aug/2024 19:46:16] "GET /favicon.ico HTTP/1.1" 404 1972

C:\Users\HP\Desktop\demo\mysite>


C:\Users\HP\Desktop\demo\mysite>python manage.py makemigrations
Migrations for 'djangoapp':
  djangoapp\migrations\0001_initial.py
    - Create model Book


C:\Users\HP\Desktop\demo\mysite>python manage.py migrate
Operations to perform:
  Apply all migrations: admin, auth, contenttypes, djangoapp, sessions
Running migrations:
  Applying contenttypes.0001_initial... OK
  Applying auth.0001_initial... OK
  Applying admin.0001_initial... OK
  Applying admin.0002_logentry_remove_auto_add... OK
  Applying admin.0003_logentry_add_action_flag_choices... OK
  Applying contenttypes.0002_remove_content_type_name... OK
  Applying auth.0002_alter_permission_name_max_length... OK
  Applying auth.0003_alter_user_email_max_length... OK
  Applying auth.0004_alter_user_username_opts... OK
  Applying auth.0005_alter_user_last_login_null... OK
  Applying auth.0006_require_contenttypes_0002... OK
  Applying auth.0007_alter_validators_add_error_messages... OK
  Applying auth.0008_alter_user_username_max_length... OK
  Applying auth.0009_alter_user_last_name_max_length... OK
  Applying auth.0010_alter_group_name_max_length... OK
  Applying auth.0011_update_proxy_permissions... OK
  Applying djangoapp.0001_initial... OK
  Applying sessions.0001_initial... OK

C:\Users\HP\Desktop\demo\mysite>


C:\Users\HP\Desktop\demo\mysite>python manage.py shell
Python 3.12.4 (tags/v3.12.4:8e8a4ba, Jun  6 2024, 19:30:16) [MSC v.1940 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
(InteractiveConsole)
>>> from djangoapp,models import Book
  File "<console>", line 1
    from djangoapp,models import Book
                  ^
SyntaxError: invalid syntax
>>> from djangoapp.models import Book
>>> Book.objects.all()
<QuerySet []>
>>> a = Book(name='Life',desc='This is the description',price=10)
>>> a.save()
>>> Book.objects.all()
<QuerySet [<Book: Book object (1)>]>
>>> exit()

C:\Users\HP\Desktop\demo\mysite>python manage.py shell
Python 3.12.4 (tags/v3.12.4:8e8a4ba, Jun  6 2024, 19:30:16) [MSC v.1940 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
(InteractiveConsole)
>>> Book.objects.all()
Traceback (most recent call last):
  File "<console>", line 1, in <module>
NameError: name 'Book' is not defined. Did you mean: 'bool'?
>>> from djangoapp.models import Book
>>> Book.objects.all()
<QuerySet [<Book: Life>]>
>>> exit()

C:\Users\HP\Desktop\demo\mysite>python manage.py shell
Python 3.12.4 (tags/v3.12.4:8e8a4ba, Jun  6 2024, 19:30:16) [MSC v.1940 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
(InteractiveConsole)
>>> from djangoapp.models import Book
>>> Book.objects.all()
<QuerySet [<Book: Life>]>
>>> exit()

C:\Users\HP\Desktop\demo\mysite>python manage.py shell
Python 3.12.4 (tags/v3.12.4:8e8a4ba, Jun  6 2024, 19:30:16) [MSC v.1940 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
(InteractiveConsole)
>>> from djangoapp.models import Book
>>> Book.objects.all()
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "C:\Users\HP\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\models\query.py", line 255, in __repr__
    return '<%s %r>' % (self.__class__.__name__, data)
                                                 ^^^^
  File "C:\Users\HP\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\models\base.py", line 518, in __repr__
    return '<%s: %s>' % (self.__class__.__name__, self)
                                                  ^^^^
TypeError: __str__ returned non-string (type tuple)
>>> exit()

C:\Users\HP\Desktop\demo\mysite>python manage.py shell
Python 3.12.4 (tags/v3.12.4:8e8a4ba, Jun  6 2024, 19:30:16) [MSC v.1940 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
(InteractiveConsole)
>>> from djangoapp.models import Book
>>> Book.objects.all()
<QuerySet [<Book: Life>]>
>>> b = Book(name='ABC',desc='bOOKS ABOUT ALPHABETS',price=15)
>>> b.save()
>>> Book.objects.all()
<QuerySet [<Book: Life>, <Book: ABC>]>
>>>


C:\Users\HP\Desktop\demo\mysite>python manage.py makemigrations
Migrations for 'djangoapp':
  djangoapp\migrations\0002_book_book_image.py
    - Add field book_image to book

C:\Users\HP\Desktop\demo\mysite>python manage.py migrate
Operations to perform:
  Apply all migrations: admin, auth, contenttypes, djangoapp, sessions
Running migrations:
  Applying djangoapp.0002_book_book_image... OK

C:\Users\HP\Desktop\demo\mysite>python manage.py runserver
Watching for file changes with StatReloader
Performing system checks...

System check identified no issues (0 silenced).
August 13, 2024 - 23:09:32
Django version 3.0, using settings 'mysite.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CTRL-BREAK.
[13/Aug/2024 23:09:37] "GET /admin/djangoapp/book/3/change/ HTTP/1.1" 200 5773
[13/Aug/2024 23:09:37] "GET /static/admin/css/fonts.css HTTP/1.1" 304 0
[13/Aug/2024 23:09:37] "GET /admin/jsi18n/ HTTP/1.1" 200 3223
[13/Aug/2024 23:09:37] "GET /static/admin/fonts/Roboto-Regular-webfont.woff HTTP/1.1" 304 0
[13/Aug/2024 23:09:37] "GET /static/admin/fonts/Roboto-Light-webfont.woff HTTP/1.1" 304 0
[13/Aug/2024 23:09:37] "GET /static/admin/fonts/Roboto-Bold-webfont.woff HTTP/1.1" 304 0
[13/Aug/2024 23:09:40] "GET /admin/djangoapp/book/3/change/default.jpg HTTP/1.1" 301 0
[13/Aug/2024 23:09:40] "GET /admin/djangoapp/book/3/change/default.jpg/ HTTP/1.1" 302 0
[13/Aug/2024 23:09:40] "GET /admin/djangoapp/book/3/change/default.jpg/change/ HTTP/1.1" 302 0
[13/Aug/2024 23:09:40] "GET /admin/ HTTP/1.1" 200 4219
[13/Aug/2024 23:09:41] "GET /static/admin/img/icon-alert.svg HTTP/1.1" 200 504

C:\Users\HP\Desktop\demo\mysite>

use pip install pillow to include image files in django






























































